--INSERT DATA
INSERT INTO T_MARVEL
(MARVEL_ID, NAME, CATEGORY, GENDER, HOME, INTELLIGENCE, STRENGTH, SPEED, FIGHTING_SKILLS, ROW_CREATE_TSP)
VALUES
(1, 'SPIDER MAN', 'HERO', 'MALE', 'USA', 'GIFTED', 'SUPERHUMAN', 'SUPERHUMAN', 'EXPERIENCED FIGHTER', CURRENT_TIMESTAMP),
(2, 'IRON MAN', 'HERO', 'MALE', 'USA', 'SUPER-GENIUS', 'SUPERHUMAN', 'SUPERSONIC', 'EXPERIENCED FIGHTER', CURRENT_TIMESTAMP),
(3, 'HULK', 'HERO', 'MALE', 'USA', 'SUPER-GENIUS', 'INCALCULABLE', 'SUPERHUMAN', 'EXPERIENCED FIGHTER', CURRENT_TIMESTAMP),
(4, 'LOKI', 'VILLAIN', 'MALE', 'JOTUNHEIM', 'GENIUS', 'SUPERHUMAN', 'WARP SPEED', 'SOME TRAINING', CURRENT_TIMESTAMP),
(5, 'DOCTOR DOOM', 'VILLAIN', 'MALE', 'LATVERIA', 'SUPER-GENIUS', 'SUPERHUMAN', 'SUPERSONIC', 'EXPERIENCED FIGHTER', CURRENT_TIMESTAMP),
(6, 'STORM', 'HERO', 'FEMALE', 'KENYA', 'NORMAL', 'NORMAL', 'SUPERHUMAN', 'EXPERIENCED FIGHTER', CURRENT_TIMESTAMP),
(7, 'WOLVERINE', 'HERO', 'MALE', 'CANADA', 'NORMAL', 'SUPERHUMAN', 'NORMAL', 'MASTER OF ALL FORMS OF COMBAT', CURRENT_TIMESTAMP),
(8, 'THOR', 'HERO', 'MALE', 'NORWAY', 'NORMAL', 'INCALCULABLE', 'WARP SPEED', 'EXPERIENCED FIGHTER', CURRENT_TIMESTAMP),
(9, 'ROGUE', 'HERO', 'FEMALE', 'USA', 'OMNISCIENT', 'INCALCULABLE', 'WARP SPEED', 'MASTER OF ALL FORMS OF COMBAT', CURRENT_TIMESTAMP),
(10, 'GREEN GOBLIN', 'VILLAIN', 'MALE', 'USA', 'GIFTED', 'SUPERHUMAN', 'SUPERHUMAN', 'SOME TRAINING', CURRENT_TIMESTAMP);

--INSERT DATA
INSERT INTO T_DC
(DC_ID, NAME, CATEGORY, GENDER, IDENTITY, ROW_CREATE_TSP)
VALUES
(1, 'BATMAN', 'HERO', 'MALE', 'SECRET', CURRENT_TIMESTAMP),
(2, 'SUPERMAN', 'HERO', 'MALE', 'SECRET', CURRENT_TIMESTAMP),
(3, 'WONDER WOMAN', 'HERO', 'FEMALE', 'PUBLIC', CURRENT_TIMESTAMP),
(4, 'TALIA AL GHUL', 'VILLAIN', 'FEMALE', 'SECRET', CURRENT_TIMESTAMP),
(5, 'CATWOMAN', 'HERO', 'FEMALE', 'SECRET', CURRENT_TIMESTAMP),
(6, 'AQUAMAN', 'HERO', 'MALE', 'PUBLIC', CURRENT_TIMESTAMP),
(7, 'LEX LUTHOR', 'VILLAIN', 'MALE', 'PUBLIC', CURRENT_TIMESTAMP),
(8, 'JOKER', 'VILLAIN', 'MALE', 'SECRET', CURRENT_TIMESTAMP),
(9, 'GREEN LANTERN', 'HERO', 'MALE', 'SECRET', CURRENT_TIMESTAMP),
(10, 'FLASH', 'HERO', 'MALE', 'SECRET', CURRENT_TIMESTAMP);